parameters:
    xidea_account.account.form.type.class: Xidea\Bundle\AccountBundle\Form\Type\AccountType
    xidea_account.account.form.create.factory.default.class: Xidea\Bundle\BaseBundle\Form\Factory\FormFactory
    xidea_account.account.form.create.handler.default.class: Xidea\Bundle\AccountBundle\Form\Handler\AccountFormHandler

services:
    xidea_account.account.form.type:
        class: %xidea_account.account.form.type.class%
        arguments:
            - %xidea_account.account.class%
        tags:
            - { name: form.type, alias: "xidea_account" }
    xidea_account.account.form.create.factory.default:
        class: %xidea_account.account.form.create.factory.default.class%
        arguments:
            - @form.factory
            - %xidea_account.account.form.create.name%
            - %xidea_account.account.form.create.type%
            - %xidea_account.account.form.create.validation_groups%
    xidea_account.account.form.create.handler.default:
        class: %xidea_account.account.form.create.handler.default.class%
        arguments:
            - @xidea_account.account.form.create.factory
            - @event_dispatcher