parameters:
    xidea_account.controller.list.class: Xidea\Bundle\AccountBundle\Controller\ListController
    xidea_account.controller.show.class: Xidea\Bundle\AccountBundle\Controller\ShowController
    xidea_account.controller.create.class: Xidea\Bundle\AccountBundle\Controller\CreateController
  
services:
    xidea_account.controller.list:
        class: %xidea_account.controller.list.class%
        arguments:
            - @xidea_account.account.configuration
            - @xidea_account.account.loader
        calls:
            - [setEventDispatcher, [@event_dispatcher]]
            - [setTemplateManager, [@xidea_base.template_manager]]
    xidea_account.controller.show:
        class: %xidea_account.controller.show.class%
        arguments:
            - @xidea_account.account.configuration
            - @xidea_account.account.loader
        calls:
            - [setEventDispatcher, [@event_dispatcher]]
            - [setTemplateManager, [@xidea_base.template_manager]]
    xidea_account.controller.create:
        class: %xidea_account.controller.create.class%
        arguments:
            - @xidea_account.account.configuration
            - @xidea_account.account.factory
            - @xidea_account.account.manager
            - @xidea_account.account.form.handler
        calls:
            - [setEventDispatcher, [@event_dispatcher]]
            - [setRouter, [@router]]
            - [setTemplateManager, [@xidea_base.template_manager]]