xidea_account_list:
    path:  /accounts
    defaults: { _controller: xidea_account.controller.list:listAction }
 
xidea_account_show:
    path:  /accounts/{id}
    defaults: { _controller: xidea_account.controller.show:showAction }
    requirements:
        id:  \d+
    
xidea_account_create:
    path:  /accounts/create
    defaults: { _controller: xidea_account.controller.create:createAction }